force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
  <label>Item</label>
  <pluralLabel>Items</pluralLabel>
  <nameField>
    <type>Text</type>
    <label>Item Name</label>
  </nameField>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Description__c.field-meta.xml
<CustomField>
  <fullName>Description__c</fullName>
  <label>Description</label>
  <type>Text</type>
  <length>255</length>
</CustomField>

force-app/main/default/objects/Item__c/fields/Family__c.field-meta.xml
<CustomField>
  <fullName>Family__c</fullName>
  <label>Family</label>
  <type>Picklist</type>
  <valueSet>
    <valueSetDefinition>
      <value><fullName>Laptops</fullName><default>true</default></value>
      <value><fullName>Phones</fullName><default>false</default></value>
      <value><fullName>Headphones</fullName><default>false</default></value>
    </valueSetDefinition>
  </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Image__c.field-meta.xml
<CustomField>
  <fullName>Image__c</fullName>
  <label>Image</label>
  <type>Url</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
  <fullName>Price__c</fullName>
  <label>Price</label>
  <type>Number</type>
  <precision>16</precision>
  <scale>2</scale>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
  <fullName>Type__c</fullName>
  <label>Type</label>
  <type>Picklist</type>
  <valueSet>
    <valueSetDefinition>
      <value><fullName>Standard</fullName><default>false</default></value>
      <value><fullName>Pro</fullName><default>false</default></value>
    </valueSetDefinition>
  </valueSet>
</CustomField>

force-app/main/default/classes/ItemService.cls
public with sharing class ItemService {
    public class Result {
        @AuraEnabled public List<Item__c> items;
        @AuraEnabled public Integer total;
    }

    @AuraEnabled(cacheable=true)
    public static Result searchItems(String family, String type, String q, Integer limitSize, Integer offsetSize){
        String soql = 'SELECT Id, Name, Family__c, Type__c, Price__c, Image__c FROM Item__c WHERE Id != null';
        if(String.isNotBlank(family)) soql += ' AND Family__c = :family';
        if(String.isNotBlank(type))   soql += ' AND Type__c   = :type';
        if (String.isNotBlank(q)) {
        soql += ' AND (Name LIKE :(\'%' + q + '%\') OR Description__c LIKE :(\'%' + q + '%\'))';
    }

        String countSoql = soql.replace('SELECT Id, Name, Family__c, Type__c, Price__c, Image__c','SELECT COUNT()');

        soql += ' ORDER BY Name LIMIT :limitSize OFFSET :offsetSize';
        Result r = new Result();
        r.items = Database.query(soql);
        r.total = (Integer)Database.countQuery(countSoql);
        return r;
    }
}